### PR TITLE
Add from_Pose_msg to tf

### PR DESCRIPTION
**Pull request by jpanikulam**
Lacking things like this is one of my greatest frustrations with rospy tf.

### CODE REVIEW

**Comment by forrestv** [comment]
Can you change the commit to conform to the existing indentation? The entire file is munged. Regardless of whether the existing indentation is ideal or not, this is not the pull request to fix it in.

**Comment by forrestv** [comment]
I'll merge once that's fixed.

**Comment by jpanikulam** [comment]
Oops. This doesn't change any indentation, Sublime just autoremoved trailing whitespace on the newlines.

Will fix

**Comment by jpanikulam** [comment]
fix't

**Pull request merged**
