### PR TITLE
Add get_last_message_time to subscriber

### PR DESCRIPTION
**Pull request by mattlangford**
Adding for use on sub

### CODE REVIEW

**Comment by forrestv** [comment]
Your patch breaks when simulated time is enabled, as Semaphore revealed. See the txros README for how to run the test cases locally.

It appears that this could be fixed by moving the setting of self._last_message and self._last_message_time below calling the callback, which would change the semantics of Subscriber a bit, but is probably fine.

That said, I don't really see a huge need for this. Why doesn't your message have a timestamp? Why can't you use it? From my experience, actually getting the current time can usually be avoided and indeed should be avoided as much as possible.

**Comment by forrestv** [comment]
Also, did you get an email notification that the Semaphore build failed? Just wondering.

**Comment by mattlangford** [comment]
I did not get an email or any notifications for the build fail.

So the script I am writing will be used for running simulation jobs with Gazebo. Ideally we would be able to loop a mission all night with different initial conditions and be able to see what happens if the mission fails. The way I am doing this is by continuously caching data from different topics in python until a failure is reported and then dumping the data from 30 or so seconds before the failure to a bag file. Since I am not dumping to the bag file as soon as I get the message, I have to keep timestamps of when the message was received so that the bag will play back in real time (if I don't stamp the saved data going into the bag, it will playback all the data as if it was all published in one instant).

A problem that I see using `get_last_message` is that if some topic is publishing slowly, the last message could be from a few seconds ago and if I timestamped this old message with the current time, when we play the bag back it will look like that topic is being published faster then it actually was. The goal is to capture conditions just like they were before the crash and adding "fake" timestamps to the data (just stamping with the current time) seems like it could cause problems (it could cause issues when trying to recreate the problem maybe).

In most cases when data is coming in fast enough there wouldn't be a problem but in some cases I can foresee issues being had. What do you think?

**Comment by mattlangford** [comment]
Also, I ran into this error:

> Traceback (most recent call last):
>   File "/home/matt/Sub8_ws/src/txros/txros/src/txros/subscriber.py", line 97, in _publisher_thread
>     self._last_message_time = self._node_handle.get_time()
>   File "/home/matt/Sub8_ws/src/txros/txros/src/txros/nodehandle.py", line 245, in get_time
>     return self._sim_time
> AttributeError: 'NodeHandle' object has no attribute '_sim_time'

which I bet is the error Semaphore caught - your suggestion to move the setting down seems to fix that problem.

**Comment by forrestv** [comment]
Hmm, why are you using `get_last_message` anyway instead of a callback? It seems like a callback would be better suited to your use (recording all the messages). With `get_last_message`, you have to poll, right? If you used a callback, you could get the current time inside of it without requiring changes to txros.

Also, your recent commit stripped all the trailing whitespace, creating a lot of clutter, but your first one didn't. That needs to be fixed.

**Comment by mattlangford** [comment]
Ah shoot sorry, forgot to fix that from sublime.

I was trying to avoid storing thousands of messages in python and having to deal with deleting them after a certain amount of time. I set up a ring buffer like array to store messages at fixed intervals which means only a small number of messages are stored and writing over them is easy.

**Pull request merged**
